[package]
name = "macro_derive"
version = "0.0.1"
edition = "2021"

[lib]
name = "macro_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0.47", features = ["extra-traits", "full"] }
quote = "1.0.35"
proc-macro2 = "1.0.75"